/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.telainicial.view;

import br.com.ifba.login.view.TelaLoginUI;
import br.com.ifba.pontoturistico.view.PontoTuristicoList;
import br.com.ifba.promocao.view.PromocaoList;
import br.com.ifba.usuario.parceiro.view.ParceirosListar;
import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;

/**
 *
 * @author juant
 */
@Component
public class TelaInicial extends javax.swing.JFrame implements ApplicationContextAware{

    private ApplicationContext applicationContext;
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        
        setLocationRelativeTo(null); // inicializa o jframe no meio da tela
        // Impede que o usuário redimensione a janela
        this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCRUDPontoTuristico = new javax.swing.JButton();
        btnLogar = new javax.swing.JButton();
        btnPromocoes = new javax.swing.JButton();
        btncrudParceiros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCRUDPontoTuristico.setText("Gestão de Pontos Turisticos");
        btnCRUDPontoTuristico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCRUDPontoTuristicoActionPerformed(evt);
            }
        });

        btnLogar.setText("Logar");
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });

        btnPromocoes.setText("Gestão de Promoções");
        btnPromocoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromocoesActionPerformed(evt);
            }
        });

        btncrudParceiros.setText("Gestsão de parceiros");
        btncrudParceiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrudParceirosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPromocoes)
                            .addComponent(btncrudParceiros)
                            .addComponent(btnCRUDPontoTuristico)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(btnLogar)))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnCRUDPontoTuristico)
                .addGap(18, 18, 18)
                .addComponent(btnPromocoes)
                .addGap(18, 18, 18)
                .addComponent(btncrudParceiros)
                .addGap(42, 42, 42)
                .addComponent(btnLogar)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCRUDPontoTuristicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRUDPontoTuristicoActionPerformed
        // TODO add your handling code here:
        PontoTuristicoList telaPontoTuristicoList = applicationContext.getBean(PontoTuristicoList.class);
        telaPontoTuristicoList.setVisible(true);
    }//GEN-LAST:event_btnCRUDPontoTuristicoActionPerformed

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed
        TelaLoginUI telaLogin = applicationContext.getBean(TelaLoginUI.class);
        telaLogin.setVisible(true);
    }//GEN-LAST:event_btnLogarActionPerformed

    private void btnPromocoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromocoesActionPerformed
        // TODO add your handling code here:
        PromocaoList telaPromocaoListar = applicationContext.getBean(PromocaoList.class);
        telaPromocaoListar.setVisible(true);
        
    }//GEN-LAST:event_btnPromocoesActionPerformed


    private void btncrudParceirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrudParceirosActionPerformed
       ParceirosListar crudParceiros = applicationContext.getBean(ParceirosListar.class);
       crudParceiros.setVisible(true);
    }//GEN-LAST:event_btncrudParceirosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCRUDPontoTuristico;
    private javax.swing.JButton btnLogar;
    private javax.swing.JButton btnPromocoes;
    private javax.swing.JButton btncrudParceiros;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.applicationContext = applicationContext;
    }
}
