/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.telainicial.view;

import br.com.ifba.Solicitacao.view.SolicitarParceria;
import br.com.ifba.central.view.TelaCentralInformacoesUI;
import br.com.ifba.evento.view.EventoListar;
import br.com.ifba.login.view.TelaLoginUI;
import br.com.ifba.pontoturistico.view.PontoTuristicoList;
import br.com.ifba.promocao.view.PromocaoList;
import br.com.ifba.promocao.view.TipoPromocaoList;
import br.com.ifba.sessao.UsuarioSession;
import br.com.ifba.usuario.parceiro.view.ParceirosListar;
import br.com.ifba.util.MostrarMensagem;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;

/**
 *
 * @author juant
 */
@Component
public class TelaInicial extends javax.swing.JFrame implements ApplicationContextAware{

    private ApplicationContext applicationContext;
    
    @Autowired
    private UsuarioSession usuarioSession;
    
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        
        setLocationRelativeTo(null); // inicializa o jframe no meio da tela
        // Impede que o usuário redimensione a janela
        this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCRUDPontoTuristico = new javax.swing.JButton();
        btnLogar = new javax.swing.JButton();
        btnPromocoes = new javax.swing.JButton();
        btncrudParceiros = new javax.swing.JButton();
        btnCentral = new javax.swing.JButton();
        btnSolicitar = new javax.swing.JButton();
        btnTipoPromocao = new javax.swing.JButton();
        btncrudEventos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCRUDPontoTuristico.setText("Gestão de Pontos Turisticos");
        btnCRUDPontoTuristico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCRUDPontoTuristicoActionPerformed(evt);
            }
        });

        btnLogar.setText("Logar");
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });

        btnPromocoes.setText("Gestão de Promoções");
        btnPromocoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromocoesActionPerformed(evt);
            }
        });

        btncrudParceiros.setText("Gestsão de parceiros");
        btncrudParceiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrudParceirosActionPerformed(evt);
            }
        });

        btnCentral.setText("Central de Informações Turísticas");
        btnCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentralActionPerformed(evt);
            }
        });

        btnSolicitar.setText("Solicitar Parceria");
        btnSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarActionPerformed(evt);
            }
        });

        btnTipoPromocao.setText("Gestão de Tipos de Promoções");
        btnTipoPromocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoPromocaoActionPerformed(evt);
            }
        });

        btncrudEventos.setText("Gestão de eventos");
        btncrudEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrudEventosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(btnSolicitar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPromocoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncrudParceiros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTipoPromocao, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnLogar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCRUDPontoTuristico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncrudEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCRUDPontoTuristico)
                    .addComponent(btnPromocoes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTipoPromocao)
                        .addGap(18, 18, 18)
                        .addComponent(btncrudParceiros)
                        .addGap(36, 36, 36)
                        .addComponent(btnLogar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSolicitar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCentral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncrudEventos)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCRUDPontoTuristicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRUDPontoTuristicoActionPerformed
        // TODO add your handling code here:
        PontoTuristicoList telaPontoTuristicoList = applicationContext.getBean(PontoTuristicoList.class);
        telaPontoTuristicoList.setVisible(true);
    }//GEN-LAST:event_btnCRUDPontoTuristicoActionPerformed

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed
        TelaLoginUI telaLogin = applicationContext.getBean(TelaLoginUI.class);
        telaLogin.setVisible(true);
    }//GEN-LAST:event_btnLogarActionPerformed

    private void btnPromocoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromocoesActionPerformed
        // TODO add your handling code here:
        PromocaoList telaPromocaoListar = applicationContext.getBean(PromocaoList.class);
        telaPromocaoListar.setVisible(true);
        
    }//GEN-LAST:event_btnPromocoesActionPerformed


    private void btncrudParceirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrudParceirosActionPerformed
       ParceirosListar crudParceiros = applicationContext.getBean(ParceirosListar.class);
       crudParceiros.setVisible(true);
    }//GEN-LAST:event_btncrudParceirosActionPerformed

    private void btnCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentralActionPerformed
        TelaCentralInformacoesUI central = applicationContext.getBean(TelaCentralInformacoesUI.class);
        central.setVisible(true);
    }//GEN-LAST:event_btnCentralActionPerformed

    private void btnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarActionPerformed
        if(!usuarioSession.isLogado()) {
           MostrarMensagem.erro(this, "O Usuario precisa estar logado", "Erro");
        } else {
            SolicitarParceria soc = applicationContext.getBean(SolicitarParceria.class);
            soc.setLocationRelativeTo(this); // posiciona centralizado
            soc.setVisible(true);
        }  
    }//GEN-LAST:event_btnSolicitarActionPerformed

    private void btnTipoPromocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoPromocaoActionPerformed
        // TODO add your handling code here:
        TipoPromocaoList tipo = applicationContext.getBean(TipoPromocaoList.class);
        tipo.setVisible(true);
    }//GEN-LAST:event_btnTipoPromocaoActionPerformed

    private void btncrudEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrudEventosActionPerformed
      EventoListar crudEventos = applicationContext.getBean(EventoListar.class);
        crudEventos.setVisible(true);
    }//GEN-LAST:event_btncrudEventosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCRUDPontoTuristico;
    private javax.swing.JButton btnCentral;
    private javax.swing.JButton btnLogar;
    private javax.swing.JButton btnPromocoes;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JButton btnTipoPromocao;
    private javax.swing.JButton btncrudEventos;
    private javax.swing.JButton btncrudParceiros;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.applicationContext = applicationContext;
    }
}
