/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.pontoturistico.view;

import br.com.ifba.pontoturistico.controller.PontoTuristicoIController;
import br.com.ifba.pontoturistico.entity.PontoTuristico;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author juant
 */
@Component
@Scope("prototype")
public class PontoTuristicoUpdate extends javax.swing.JFrame {

    @Autowired
    private PontoTuristicoIController pontoTuristicoController;
    private PontoTuristico pontoTuristicoEditar;
    private PontoTuristicoList pontoTuristicoLista;
    /**
     * Creates new form PontoTuristicoUpdate
     */
    public PontoTuristicoUpdate() {
        initComponents();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        
        // Impede que o usuário redimensione a janela
        this.setResizable(false);
        
        setLocationRelativeTo(null); // inicializa o jframe no meio da tela
    }
        
    // Método público para receber os dados APÓS a criação
    public void setDadosParaEdicao(PontoTuristico pontoTuristico, 
                                    PontoTuristicoList pontoTuristicoLista) {
        this.pontoTuristicoEditar = pontoTuristico;
        this.pontoTuristicoLista = pontoTuristicoLista;
        this.preencherCampos();
    }
    
    private void preencherCampos() {
        // Usa os dados do objeto pontoTuristico para preencher os componentes da tela
        txtNome.setText(this.pontoTuristicoEditar.getNome());
        txtDescricao.setText(this.pontoTuristicoEditar.getDescricao());
        sliNivelAcess.setValue(this.pontoTuristicoEditar.getNivelAcessibilidade()); 
        txtLocalizacao.setText(this.pontoTuristicoEditar.getLocalizacao());
        txtHorarioAber.setText(this.pontoTuristicoEditar.getHorarioAbertura());
        txtHorarioFecha.setText(this.pontoTuristicoEditar.getHorarioFechamento());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtLocalizacao = new javax.swing.JTextField();
        lblLocalizacao2 = new javax.swing.JLabel();
        txtHorarioAber = new javax.swing.JTextField();
        lblLocalizacao = new javax.swing.JLabel();
        sliNivelAcess = new javax.swing.JSlider();
        lblHorarioAber = new javax.swing.JLabel();
        txtHorarioFecha = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        lblHorarioFecha = new javax.swing.JLabel();
        lblInfoHorario = new javax.swing.JLabel();
        btnCancelar1 = new javax.swing.JButton();

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInfo.setText("ATUALIZAR PONTO TURISTICO");

        txtDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblDescricao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDescricao.setText("DESCRIÇÃO:");

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNome.setText("NOME:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtLocalizacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblLocalizacao2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLocalizacao2.setText("NIVEL DE ACESSIBILIDADE: (0 A 5)");

        txtHorarioAber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblLocalizacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLocalizacao.setText("LOCALIZAÇÃO: (RUA - BAIRRO) OU (PONTO DE REFERÊNCIA)");

        sliNivelAcess.setMaximum(5);
        sliNivelAcess.setValue(2);

        lblHorarioAber.setText("HORARIO DE ABERTURA");

        txtHorarioFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        lblHorarioFecha.setText("HORARIO DE FECHAMENTO");

        lblInfoHorario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInfoHorario.setText("HORÁRIO DE FUNCIONAMENTO: (hh:mm)");

        btnCancelar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar1.setText("CANCELAR");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(lblDescricao)
                                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCancelar1))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLocalizacao)
                                    .addComponent(lblLocalizacao2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtHorarioAber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblHorarioAber))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblHorarioFecha)
                                                .addComponent(txtHorarioFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(lblInfoHorario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sliNivelAcess, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtLocalizacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnAtualizar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(lblInfo)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLocalizacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblLocalizacao2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sliNivelAcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblInfoHorario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblHorarioAber)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHorarioAber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblHorarioFecha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHorarioFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizar)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        try {
            if (txtNome.getText().equals("") ||
                txtDescricao.getText().equals("") ||
                txtLocalizacao.getText().equals("") ||
                txtHorarioAber.getText().equals("") ||
                txtHorarioFecha.getText().equals("")) {
                JOptionPane.showMessageDialog(
                    null, "Existem campos vazios ou invalido(s), preencha todos e tente novamente!",
                    "Alerta", JOptionPane.WARNING_MESSAGE);
            }
            else{
                pontoTuristicoEditar.setNome(txtNome.getText());
                pontoTuristicoEditar.setDescricao(txtDescricao.getText());
                pontoTuristicoEditar.setLocalizacao(txtLocalizacao.getText());
                pontoTuristicoEditar.setNivelAcessibilidade(sliNivelAcess.getValue());
                pontoTuristicoEditar.setHorarioAbertura(txtHorarioAber.getText());
                pontoTuristicoEditar.setHorarioFechamento(txtHorarioFecha.getText());

                // atualiza o objeto no banco
                pontoTuristicoController.update(pontoTuristicoEditar);

                // Exibe uma mensagem de sucesso para o usuário
                JOptionPane.showMessageDialog(this, "Ponto Turistico atualizado com sucesso!",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                // possibilita a atualização instantanea da tabela da tela inicial
                this.pontoTuristicoLista.carregarDados();

                // FECHA A TELA ATUAL (A TELA DE CADASTRO)
                this.dispose(); // <--- É esta linha que fecha a janela!
            }
        }
        catch (Exception e){
            // Em caso de erro, exibe uma mensagem e NÃO fecha a tela
            JOptionPane.showMessageDialog(this,
                "Ocorreu um erro ao cadastrar: " +
                e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        // FECHA A TELA ATUAL (A TELA DE CADASTRO)
        this.dispose(); // <--- É esta linha que fecha a janela!
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        // TODO add your handling code here:
        // FECHA A TELA ATUAL (A TELA DE CADASTRO)
        this.dispose(); // <--- É esta linha que fecha a janela!
    }//GEN-LAST:event_btnCancelar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblHorarioAber;
    private javax.swing.JLabel lblHorarioFecha;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblInfoHorario;
    private javax.swing.JLabel lblLocalizacao;
    private javax.swing.JLabel lblLocalizacao2;
    private javax.swing.JLabel lblNome;
    private javax.swing.JSlider sliNivelAcess;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtHorarioAber;
    private javax.swing.JTextField txtHorarioFecha;
    private javax.swing.JTextField txtLocalizacao;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
