/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.pontoturistico.view;

import br.com.ifba.endereco.entity.Endereco;
import br.com.ifba.pontoturistico.controller.PontoTuristicoIController;
import br.com.ifba.pontoturistico.entity.PontoTuristico;
import br.com.ifba.sessao.UsuarioSession;
import br.com.ifba.gestor.entity.Gestor;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author juant
 */
@Component
@Scope("prototype") // Garante que cada clique em "Adicionar" crie uma janela nova
public class PontoTuristicoSave extends javax.swing.JFrame {

    @Autowired
    private final PontoTuristicoIController pontoTuristicoController;
    
    private UsuarioSession userLogado;
    
    
    private PontoTuristicoList pontoTuristicoList;
    
    /**
     * Creates new form PontoTuristicoSave
     * @param pontoTuristicoController
     * @param userLogado
     */
    public PontoTuristicoSave(PontoTuristicoIController pontoTuristicoController, UsuarioSession userLogado) {
        // inicializa o controller como parametro recebido
        this.pontoTuristicoController = pontoTuristicoController;
        this.userLogado = userLogado;
        
        initComponents();
        
        setLocationRelativeTo(null); // inicializa o jframe no meio da tela
        // Impede que o usuário redimensione a janela
        this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
    }
    
    // Ele será chamado pela PontoTuristicoList_OLD para "entregar" a referência dela mesma.
    public void setPontoTuristicoList(PontoTuristicoList pontoTuristicoList) {
        this.pontoTuristicoList = pontoTuristicoList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome4 = new javax.swing.JTextField();
        lblLocalizacao1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblHorarioAber = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtDescricao = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        txtHorarioAber = new javax.swing.JTextField();
        txtHorarioFecha = new javax.swing.JTextField();
        lblHorarioFecha = new javax.swing.JLabel();
        lblInfoHorario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtEstado = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        lblLocalizacao2 = new javax.swing.JLabel();
        sliNivelAcess = new javax.swing.JSlider();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblRua = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();

        txtNome4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblLocalizacao1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLocalizacao1.setText("LOCALIZAÇÃO: (RUA - BAIRRO) OU (PONTO DE REFERÊNCIA)");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNome.setText("NOME:");

        lblHorarioAber.setText("HORARIO DE ABERTURA");

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        lblInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInfo.setText("CADASTRO DE PONTOS TURISTICOS");

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblDescricao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDescricao.setText("DESCRIÇÃO:");

        txtHorarioAber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtHorarioFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblHorarioFecha.setText("HORARIO DE FECHAMENTO");

        lblInfoHorario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInfoHorario.setText("HORÁRIO DE FUNCIONAMENTO: (HH:mm)");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstado.setText("ESTADO:");

        lblLocalizacao2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLocalizacao2.setText("NIVEL DE ACESSIBILIDADE: (0 A 5)");

        sliNivelAcess.setMaximum(5);
        sliNivelAcess.setValue(2);

        lblBairro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBairro.setText("BAIRRO:");

        txtBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblRua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRua.setText("RUA:");

        txtRua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNumero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumero.setText("Nº:");

        txtNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblCidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCidade.setText("CIDADE:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(lblInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescricao)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInfoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHorarioAber)
                                .addGap(46, 46, 46)
                                .addComponent(lblHorarioFecha))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHorarioAber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(txtHorarioFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEstado)
                                .addGap(126, 126, 126)
                                .addComponent(lblCidade))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblBairro)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRua)
                                .addGap(242, 242, 242)
                                .addComponent(lblNumero))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(txtNumero))
                            .addComponent(lblLocalizacao2)
                            .addComponent(sliNivelAcess, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBairro)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(btnCancelar)
                        .addGap(36, 36, 36)
                        .addComponent(btnCadastrar)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblInfo)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(6, 6, 6)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblDescricao)
                        .addGap(6, 6, 6)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblInfoHorario)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHorarioAber)
                            .addComponent(lblHorarioFecha))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHorarioAber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHorarioFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblEstado))
                            .addComponent(lblCidade))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(lblBairro)
                        .addGap(4, 4, 4)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRua)
                            .addComponent(lblNumero))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(lblLocalizacao2)
                        .addGap(14, 14, 14)
                        .addComponent(sliNivelAcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnCadastrar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        try {
            if (txtNome.getText().equals("") || 
                        txtDescricao.getText().equals("") || 
                        txtEstado.getText().equals("") ||
                        txtCidade.getText().equals("") ||
                        txtBairro.getText().equals("") ||
                        txtRua.getText().equals("") ||
                        txtHorarioAber.getText().equals("") ||
                        txtHorarioFecha.getText().equals("")) {
                JOptionPane.showMessageDialog(
                    null, "Existem campos vazios ou invalido(s), preencha todos e tente novamente!",
                    "Alerta", JOptionPane.WARNING_MESSAGE);
            }
            else{
                // Atribui os dados de Endereco ao objeto para inserção no campo de localizacao do PontoTuristico
                Endereco enderecoPonto = new Endereco();
                enderecoPonto.setEstado(txtEstado.getText());
                enderecoPonto.setCidade(txtCidade.getText());
                enderecoPonto.setBairro(txtBairro.getText());
                enderecoPonto.setRua(txtRua.getText());
                enderecoPonto.setNumero(txtNumero.getText());
                
                // Obtém o gestor da sessão
                Gestor gestorResponsavel = (Gestor) userLogado.getUsuarioLogado().getPessoa();
                
                // Atribui os dados de PontoTuristico ao objeto
                PontoTuristico novoPonto = new PontoTuristico();
                novoPonto.setNome(txtNome.getText());
                novoPonto.setDescricao(txtDescricao.getText());
                novoPonto.setEndereco(enderecoPonto);
                novoPonto.setNivelAcessibilidade(sliNivelAcess.getValue());
                novoPonto.setHorarioAbertura(txtHorarioAber.getText());
                novoPonto.setHorarioFechamento(txtHorarioFecha.getText());
                novoPonto.setGestor(gestorResponsavel);
                
                

                // salva o objeto no banco
                pontoTuristicoController.save(novoPonto);

                // Exibe uma mensagem de sucesso para o usuário
                JOptionPane.showMessageDialog(this, "Ponto Turistico cadastrado com sucesso!",
                                            "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                
                // possibilita a atualização instantanea da tabela da tela inicial
                this.pontoTuristicoList.carregarDados();
                
                // FECHA A TELA ATUAL (A TELA DE CADASTRO)
                this.dispose(); // <--- É esta linha que fecha a janela!
            }
        }
        catch (Exception e){
            // Em caso de erro, exibe uma mensagem e NÃO fecha a tela
            JOptionPane.showMessageDialog(this,
                "Ocorreu um erro ao cadastrar: " +
                e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        // FECHA A TELA ATUAL (A TELA DE CADASTRO)
        this.dispose(); // <--- É esta linha que fecha a janela!
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblHorarioAber;
    private javax.swing.JLabel lblHorarioFecha;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblInfoHorario;
    private javax.swing.JLabel lblLocalizacao1;
    private javax.swing.JLabel lblLocalizacao2;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRua;
    private javax.swing.JSlider sliNivelAcess;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtHorarioAber;
    private javax.swing.JTextField txtHorarioFecha;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome4;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
