/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.promocao.view;

import br.com.ifba.promocao.controller.PromocaoIController;
import br.com.ifba.promocao.entity.Promocao;
import br.com.ifba.telainicial.view.TelaInicial;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import lombok.NoArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author Joice
 */
@NoArgsConstructor
@Component
public class PromocaoCadastrar extends javax.swing.JFrame {
    
    @Autowired
    private PromocaoIController promocaoController;

    /**
     * Creates new form PromocoesCadastrar
     */
    public PromocaoCadastrar(PromocaoIController controller) {
    this.promocaoController = controller;
    initComponents();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblTituloTela = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblRegras = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblDataInicio = new javax.swing.JLabel();
        lblDataTermino = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();
        cbbTipo = new javax.swing.JComboBox<>();
        txtTitulo = new javax.swing.JTextField();
        txtRegras = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtDataInicio = new javax.swing.JTextField();
        txtDataTermino = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(102, 139, 195));

        lblTituloTela.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloTela.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloTela.setText("CADASTRO DE PROMOÇÕES, CUPONS E PACOTES");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 51));
        lblTitulo.setText("TITULO");

        lblRegras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRegras.setForeground(new java.awt.Color(0, 0, 51));
        lblRegras.setText("REGRAS");

        lblDescricao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(0, 0, 51));
        lblDescricao.setText("DESCRIÇÃO");

        lblDataInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDataInicio.setForeground(new java.awt.Color(0, 0, 51));
        lblDataInicio.setText("DATA DE INICIO");

        lblDataTermino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDataTermino.setForeground(new java.awt.Color(0, 0, 51));
        lblDataTermino.setText("DATA DE TERMINO");

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(0, 0, 51));
        lblTipo.setText("TIPO");

        btnListar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(0, 0, 51));
        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        cbbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROMOÇÃO", "CUPOM", "PACOTE" }));

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 0, 51));
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 51));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloTela, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegras)
                    .addComponent(txtRegras, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(lblDataInicio)
                        .addGap(60, 60, 60)
                        .addComponent(lblDataTermino)
                        .addGap(33, 33, 33)
                        .addComponent(lblTipo))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(cbbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(288, 288, 288)
                        .addComponent(btnHome)
                        .addGap(5, 5, 5)
                        .addComponent(btnListar)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTituloTela)
                .addGap(28, 28, 28)
                .addComponent(lblTitulo)
                .addGap(5, 5, 5)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblRegras)
                .addGap(5, 5, 5)
                .addComponent(txtRegras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblDescricao)
                .addGap(5, 5, 5)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataInicio)
                    .addComponent(lblDataTermino)
                    .addComponent(lblTipo))
                .addGap(5, 5, 5)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addComponent(btnHome)
                    .addComponent(btnListar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
    String titulo = txtTitulo.getText();
    String regras = txtRegras.getText();
    String descricao = txtDescricao.getText();
    String dataInicioStr = txtDataInicio.getText();
    String dataTerminoStr = txtDataTermino.getText();
    String tipo = (String) cbbTipo.getSelectedItem();

    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    try {
        LocalDate dataInicio = LocalDate.parse(dataInicioStr, formatter);
        LocalDate dataTermino = LocalDate.parse(dataTerminoStr, formatter);

        Date dataInicioDate = Date.from(dataInicio.atStartOfDay(ZoneId.systemDefault()).toInstant());
        Date dataTerminoDate = Date.from(dataTermino.atStartOfDay(ZoneId.systemDefault()).toInstant());

        Promocao promocao = new Promocao();
        promocao.setTitulo(titulo);
        promocao.setRegras(regras);
        promocao.setDescricao(descricao);
        promocao.setDataInicio(dataInicioDate);
        promocao.setDataTermino(dataTerminoDate);
        promocao.setTipo(tipo);

        promocaoController.save(promocao);

        JOptionPane.showMessageDialog(this, "Promoção salva com sucesso!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Formato de data inválido. Use dd/MM/yyyy.");
    }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        TelaInicial telaInicial = new TelaInicial();
        telaInicial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        PromocaoListar telaListar = new PromocaoListar();
        telaListar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbbTipo;
    private javax.swing.JLabel lblDataInicio;
    private javax.swing.JLabel lblDataTermino;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblRegras;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloTela;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtDataInicio;
    private javax.swing.JTextField txtDataTermino;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtRegras;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
