/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.promocao.view;

import br.com.ifba.promocao.controller.PromocaoController;
import br.com.ifba.promocao.controller.PromocaoIController;
import br.com.ifba.promocao.entity.Promocao;
import br.com.ifba.telainicial.view.TelaInicial;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author Joice
 */
@Component
public class PromocaoEditar extends javax.swing.JFrame {
    
    @Autowired
    private PromocaoIController promocaoController;
    
    private Promocao promocaoAtual;


    /**
     * Creates new form PromocoesEditar
     */
    public PromocaoEditar() {
        initComponents();
    }
    
    public void carregarPromocao(Promocao promocao) {
    this.promocaoAtual = promocao;
    txtTitulo.setText(promocao.getTitulo());
    txtRegras.setText(promocao.getRegras());
    txtDescricao.setText(promocao.getDescricao());
    txtDataInicio.setText(promocao.getDataInicio().toString()); // yyyy-MM-dd
    txtDataTermino.setText(promocao.getDataTermino().toString());
    cbbTipo.setSelectedItem(promocao.getTipo());
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloTela = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblRegras = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblDataInicio = new javax.swing.JLabel();
        lblDataTermino = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        cbbTipo = new javax.swing.JComboBox<>();
        txtTitulo = new javax.swing.JTextField();
        txtRegras = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtDataInicio = new javax.swing.JTextField();
        txtDataTermino = new javax.swing.JTextField();
        btnHome = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 139, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloTela.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloTela.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloTela.setText("EDIÇÃO DE PROMOÇÕES, CUPONS E PACOTES");
        jPanel1.add(lblTituloTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 540, -1));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 51));
        lblTitulo.setText("TITULO");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        lblRegras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRegras.setForeground(new java.awt.Color(0, 0, 51));
        lblRegras.setText("REGRAS");
        jPanel1.add(lblRegras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        lblDescricao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(0, 0, 51));
        lblDescricao.setText("DESCRIÇÃO");
        jPanel1.add(lblDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        lblDataInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDataInicio.setForeground(new java.awt.Color(0, 0, 51));
        lblDataInicio.setText("DATA DE INICIO");
        jPanel1.add(lblDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        lblDataTermino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDataTermino.setForeground(new java.awt.Color(0, 0, 51));
        lblDataTermino.setText("DATA DE TERMINO");
        jPanel1.add(lblDataTermino, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(0, 0, 51));
        lblTipo.setText("TIPO");
        jPanel1.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 0, 51));
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        cbbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROMOCAO", "CUPOM", "PACOTE" }));
        jPanel1.add(cbbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 170, -1));
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 570, -1));
        jPanel1.add(txtRegras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 570, 50));
        jPanel1.add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 570, 90));
        jPanel1.add(txtDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 170, -1));
        jPanel1.add(txtDataTermino, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 170, -1));

        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 51));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, -1, -1));

        btnListar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(0, 0, 51));
        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jPanel1.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        TelaInicial telaInicial = new TelaInicial();
        telaInicial.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        PromocaoListar telaListar = new PromocaoListar();
        telaListar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
         try {
        String titulo = txtTitulo.getText();
        String regras = txtRegras.getText();
        String descricao = txtDescricao.getText();
        String dataInicioStr = txtDataInicio.getText();
        String dataTerminoStr = txtDataTermino.getText();
        String tipo = (String) cbbTipo.getSelectedItem();

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

        LocalDate dataInicio = LocalDate.parse(txtDataInicio.getText(), formatter);
        LocalDate dataTermino = LocalDate.parse(txtDataTermino.getText(), formatter);

        Date dataInicioDate = Date.from(dataInicio.atStartOfDay(ZoneId.systemDefault()).toInstant());
        Date dataTerminoDate = Date.from(dataTermino.atStartOfDay(ZoneId.systemDefault()).toInstant());

        promocaoAtual.setTitulo(titulo);
        promocaoAtual.setRegras(regras);
        promocaoAtual.setDescricao(descricao);
        promocaoAtual.setDataInicio(dataInicioDate);
        promocaoAtual.setDataTermino(dataTerminoDate);
        promocaoAtual.setTipo(tipo);

        // Atualiza via controller
        //PromocaoController controller = new PromocaoController();
        promocaoController.update(promocaoAtual);

        JOptionPane.showMessageDialog(this, "Promoção atualizada com sucesso!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao salvar promoção: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSalvarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbbTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDataInicio;
    private javax.swing.JLabel lblDataTermino;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblRegras;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloTela;
    private javax.swing.JTextField txtDataInicio;
    private javax.swing.JTextField txtDataTermino;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtRegras;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
