/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.promocao.view;

import br.com.ifba.promocao.controller.PublicoPromocaoController;
import br.com.ifba.promocao.entity.PublicoPromocao;
import br.com.ifba.sessao.UsuarioSession;
import br.com.ifba.telainicial.view.TelaInicial;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;

/**
 *
 * @author Joice
 */
@Component
public class PublicoPromocaoUpdate extends javax.swing.JFrame {
    
    @Autowired
    private PublicoPromocaoController controller;

    @Autowired
    private UsuarioSession userLogado;

    @Autowired
    private ApplicationContext context;

    private PublicoPromocao publicoAtual;
    /**
     * Creates new form PublicoPromocaoUpdate
     */
    @Autowired
    public PublicoPromocaoUpdate(PublicoPromocaoController controller, UsuarioSession userLogado) {
        this.controller = controller;
        this.userLogado = userLogado;
        initComponents();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
    }
        
    // Método público que preenche os campos e armazena o objeto atual
    public void carregarPublico(PublicoPromocao publico) {
        this.publicoAtual = publico;
        txtNome.setText(publico.getNome());
        txtDescricao.setText(publico.getDescricao());
        txtFaixaEtaria.setText(publico.getFaixaEtaria());
        txtInteresse.setText(publico.getInteresse());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTituloTela = new javax.swing.JLabel();
        lbLNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblFaixaEtaria = new javax.swing.JLabel();
        txtFaixaEtaria = new javax.swing.JTextField();
        lblInteresse = new javax.swing.JLabel();
        txtInteresse = new javax.swing.JTextField();
        btnSalvar1 = new javax.swing.JButton();
        btnHome1 = new javax.swing.JButton();
        btnListar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 139, 195));

        lblTituloTela.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloTela.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloTela.setText("CADASTRAR PÚBLICO ALVO");

        lbLNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbLNome.setForeground(new java.awt.Color(0, 0, 51));
        lbLNome.setText("NOME");

        lblDescricao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(0, 0, 51));
        lblDescricao.setText("DESCRIÇÃO");

        lblFaixaEtaria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFaixaEtaria.setForeground(new java.awt.Color(0, 0, 51));
        lblFaixaEtaria.setText("FAIXA ETARIA");

        lblInteresse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInteresse.setForeground(new java.awt.Color(0, 0, 51));
        lblInteresse.setText("AREA DE INTERESSE");

        btnSalvar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalvar1.setForeground(new java.awt.Color(0, 0, 51));
        btnSalvar1.setText("SALVAR");
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });

        btnHome1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHome1.setForeground(new java.awt.Color(0, 0, 51));
        btnHome1.setText("HOME");
        btnHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome1ActionPerformed(evt);
            }
        });

        btnListar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnListar1.setForeground(new java.awt.Color(0, 0, 51));
        btnListar1.setText("LISTAR");
        btnListar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSalvar1)
                        .addGap(288, 288, 288)
                        .addComponent(btnHome1)
                        .addGap(5, 5, 5)
                        .addComponent(btnListar1))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbLNome)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDescricao)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFaixaEtaria)
                        .addComponent(txtFaixaEtaria, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblInteresse)
                        .addComponent(txtInteresse, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloTela, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTituloTela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbLNome)
                .addGap(5, 5, 5)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDescricao)
                .addGap(5, 5, 5)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFaixaEtaria)
                .addGap(5, 5, 5)
                .addComponent(txtFaixaEtaria, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblInteresse)
                .addGap(5, 5, 5)
                .addComponent(txtInteresse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar1)
                    .addComponent(btnHome1)
                    .addComponent(btnListar1))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed
        if (publicoAtual == null) {
            JOptionPane.showMessageDialog(this, "Nenhum público selecionado para atualizar.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nome = txtNome.getText().trim();
        String descricao = txtDescricao.getText().trim();
        String faixaEtaria = txtFaixaEtaria.getText().trim();
        String interesse = txtInteresse.getText().trim();

        if (nome.isEmpty() || descricao.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome e Descrição são obrigatórios!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            publicoAtual.setNome(nome);
            publicoAtual.setDescricao(descricao);
            publicoAtual.setFaixaEtaria(faixaEtaria);
            publicoAtual.setInteresse(interesse);

            controller.update(Long.MIN_VALUE, publicoAtual);

            JOptionPane.showMessageDialog(this, "Público atualizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            PublicoPromocaoList lista = context.getBean(PublicoPromocaoList.class);
            lista.setVisible(true);
            lista.carregarDados();
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar público: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvar1ActionPerformed

    private void btnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome1ActionPerformed
        // TODO add your handling code here:
        TelaInicial telaInicial = new TelaInicial();
        telaInicial.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_btnHome1ActionPerformed

    private void btnListar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListar1ActionPerformed
        // TODO add your handling code here:
        PublicoPromocaoList telaListar = context.getBean(PublicoPromocaoList.class);
        telaListar.setVisible(true);
        telaListar.carregarDados();
        this.dispose();

    }//GEN-LAST:event_btnListar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome1;
    private javax.swing.JButton btnListar1;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbLNome;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblFaixaEtaria;
    private javax.swing.JLabel lblInteresse;
    private javax.swing.JLabel lblTituloTela;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtFaixaEtaria;
    private javax.swing.JTextField txtInteresse;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
