/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.promocao.view;

import br.com.ifba.promocao.controller.TipoPromocaoIController;
import br.com.ifba.promocao.entity.PublicoPromocao;
import br.com.ifba.promocao.entity.TipoPromocao;
import br.com.ifba.promocao.service.PublicoPromocaoService;
import br.com.ifba.sessao.UsuarioSession;
import br.com.ifba.telainicial.view.TelaInicial;
import jakarta.annotation.PostConstruct;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;

/**
 *
 * @author Joice
 */
@Component
public class TipoPromocaoUpdate extends javax.swing.JFrame {
    
    // Injeção de dependência do controller que gerencia as operações de TipoPromocao
    @Autowired
    private TipoPromocaoIController controller;
    
    @Autowired
    private UsuarioSession userLogado;
    
    @Autowired
    private PublicoPromocaoService publicoService;
    
    // Contexto do Spring para acessar outros beans gerenciados
    @Autowired
    private ApplicationContext context;
    
    // Variável para armazenar o tipo de promoção que está sendo editado
    private TipoPromocao tipoAtual;


    @Autowired
    public TipoPromocaoUpdate(TipoPromocaoIController controller, UsuarioSession userLogado, PublicoPromocaoService publicoService) {
        this.controller = controller;
        this.userLogado = userLogado;
        initComponents();
    }
    
    @PostConstruct
    public void init() {
        carregarPublicos(); // agora o publicoService já foi injetado
    }

    private void carregarPublicos() {
        // Carrega todos os públicos e preenche o combo box
        List<PublicoPromocao> publicos = publicoService.findAll();
        DefaultComboBoxModel<PublicoPromocao> model = new DefaultComboBoxModel<>();
        for (PublicoPromocao p : publicos) {
            model.addElement(p);
        }
        cbbPublicoAlvo.setModel(model);

        // Seleciona o público atual do tipo (se existir)
        if (tipoAtual != null && tipoAtual.getPublicoAlvo() != null) {
            cbbPublicoAlvo.setSelectedItem(tipoAtual.getPublicoAlvo());
        }
    }
    // Método para carregar os dados do tipo de promoção que será editado
    public void carregarTipo(TipoPromocao tipo) {
        this.tipoAtual = tipo; // Armazena o tipo recebido
        txtTitulo.setText(tipo.getTitulo()); // Preenche o campo título com o valor atual
        txtRegras.setText(tipo.getRegra());
        txtDescricao.setText(tipo.getDescricao());
        // Atualiza o combo box com o público atual
        carregarPublicos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblTituloTela = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblRegras = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();
        txtTitulo = new javax.swing.JTextField();
        txtRegras = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        lblPublicoalvo = new javax.swing.JLabel();
        cbbPublicoAlvo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(102, 139, 195));

        lblTituloTela.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloTela.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloTela.setText("EDITAR TIPOS DE PROMOÇÕES");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 51));
        lblTitulo.setText("TITULO");

        lblRegras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRegras.setForeground(new java.awt.Color(0, 0, 51));
        lblRegras.setText("REGRAS");

        lblDescricao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(0, 0, 51));
        lblDescricao.setText("DESCRIÇÃO");

        btnListar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(0, 0, 51));
        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 0, 51));
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 51));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        lblPublicoalvo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPublicoalvo.setForeground(new java.awt.Color(0, 0, 51));
        lblPublicoalvo.setText("PUBLICO ALVO");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloTela)
                .addGap(134, 134, 134))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(lblPublicoalvo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbbPublicoAlvo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegras)
                    .addComponent(txtRegras, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(288, 288, 288)
                        .addComponent(btnHome)
                        .addGap(5, 5, 5)
                        .addComponent(btnListar)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTituloTela)
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addGap(5, 5, 5)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblRegras)
                .addGap(5, 5, 5)
                .addComponent(txtRegras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblDescricao)
                .addGap(5, 5, 5)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbPublicoAlvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPublicoalvo))
                .addGap(46, 46, 46)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addComponent(btnHome)
                    .addComponent(btnListar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        TipoPromocaoList telaListar = context.getBean(TipoPromocaoList.class);
        telaListar.setVisible(true);
        telaListar.carregarDados();
        this.dispose();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        String titulo = txtTitulo.getText().trim();
        String descricao = txtDescricao.getText().trim();
        String regras = txtRegras.getText().trim();
        PublicoPromocao publicoSelecionado = (PublicoPromocao) cbbPublicoAlvo.getSelectedItem();

        if (titulo.isEmpty() || descricao.isEmpty()) {
            String mensagemErro = "";
            if (titulo.isEmpty()) mensagemErro += "• Título é obrigatório\n";
            if (descricao.isEmpty()) mensagemErro += "• Descrição é obrigatória\n";
            JOptionPane.showMessageDialog(this, mensagemErro, "Campos obrigatórios", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            tipoAtual.setTitulo(titulo);
            tipoAtual.setDescricao(descricao);
            tipoAtual.setRegra(regras.isEmpty() ? null : regras);
            tipoAtual.setPublicoAlvo(publicoSelecionado);

            TipoPromocao tipoAtualizado = controller.update(tipoAtual);

            JOptionPane.showMessageDialog(this,
                    "Tipo '" + tipoAtualizado.getTitulo() + "' atualizado com sucesso!",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);

            TipoPromocaoList listagem = context.getBean(TipoPromocaoList.class);
            listagem.setVisible(true);
            listagem.carregarDados();
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao atualizar tipo:\n" + e.getMessage(),
                    "Erro no sistema",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        TelaInicial telaInicial = new TelaInicial();
        telaInicial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<PublicoPromocao> cbbPublicoAlvo;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblPublicoalvo;
    private javax.swing.JLabel lblRegras;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloTela;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtRegras;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
