/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.promocao.view;

import br.com.ifba.promocao.controller.TipoPromocaoIController;
import br.com.ifba.promocao.entity.TipoPromocao;
import br.com.ifba.telainicial.view.TelaInicial;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;

/**
 *
 * @author Joice
 */
@Component
public class TipoPromocaoSave extends javax.swing.JFrame {

    // Injeção de dependência do controller que gerencia as operações de TipoPromocao
    @Autowired
    private TipoPromocaoIController controller;
    
    // Contexto do Spring para acessar outros beans gerenciados
    @Autowired
    private ApplicationContext context;

    /**
     * Creates new form TipoPromocaoSave
     */
    public TipoPromocaoSave() {
        initComponents();
    }
    // Método para limpar os campos do formulário
    private void limparCampos() {
        txtTitulo.setText("");       // Limpa o campo de título
        txtDescricao.setText("");    // Limpa o campo de descrição
        txtRegras.setText("");       // Limpa o campo de regras
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblTituloTela = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblRegras = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();
        txtTitulo = new javax.swing.JTextField();
        txtRegras = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(102, 139, 195));

        lblTituloTela.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloTela.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloTela.setText("CADASTRAR TIPOS DE PROMOÇÕES");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 51));
        lblTitulo.setText("TITULO");

        lblRegras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRegras.setForeground(new java.awt.Color(0, 0, 51));
        lblRegras.setText("REGRAS");

        lblDescricao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(0, 0, 51));
        lblDescricao.setText("DESCRIÇÃO");

        btnListar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(0, 0, 51));
        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 0, 51));
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 51));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegras)
                    .addComponent(txtRegras, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(288, 288, 288)
                        .addComponent(btnHome)
                        .addGap(5, 5, 5)
                        .addComponent(btnListar)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloTela)
                .addGap(100, 100, 100))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTituloTela)
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addGap(5, 5, 5)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblRegras)
                .addGap(5, 5, 5)
                .addComponent(txtRegras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblDescricao)
                .addGap(5, 5, 5)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addComponent(btnHome)
                    .addComponent(btnListar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // Obtém a instância da tela de listagem do contexto Spring
        TipoPromocaoList telaListar = context.getBean(TipoPromocaoList.class);
        telaListar.setVisible(true);  // Torna a tela visível
        telaListar.carregarDados();   // Carrega os dados atualizados
        this.dispose();               // Fecha a tela atual
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // Obtém e limpa os valores dos campos
        String titulo = txtTitulo.getText().trim();
        String regras = txtRegras.getText().trim();
        String descricao = txtDescricao.getText().trim();
        
        // VALIDAÇÕES:
        // Verifica se título foi preenchido
        if(titulo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Título é obrigatório", "Erro", JOptionPane.ERROR_MESSAGE);
            return; // Interrompe a execução se validação falhar
        }
        
        // Verifica se descrição foi preenchida
        if(descricao.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Descrição é obrigatória", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            // Cria novo objeto TipoPromocao com os dados do formulário
            TipoPromocao tipo = new TipoPromocao();
            tipo.setTitulo(titulo);
            tipo.setDescricao(descricao);
            tipo.setRegra(regras); // Regras é opcional
            
            // Chama o controller para salvar no banco de dados
            controller.save(tipo);
            
            // Feedback de sucesso para o usuário
            JOptionPane.showMessageDialog(this, "Tipo salvo com sucesso!");
            limparCampos(); // Limpa os campos após salvar
            
            // Abre a tela de listagem com os dados atualizados
            TipoPromocaoList listagem = context.getBean(TipoPromocaoList.class);
            listagem.setVisible(true);
            listagem.carregarDados();
            this.dispose(); // Fecha a tela atual
            
        } catch (Exception e) {
            // Tratamento de erro genérico
            JOptionPane.showMessageDialog(this, 
                "Erro ao salvar tipo: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        TelaInicial telaInicial = new TelaInicial();
        telaInicial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoPromocaoSave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoPromocaoSave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoPromocaoSave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoPromocaoSave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoPromocaoSave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblRegras;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloTela;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtRegras;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
